# ~/.config/alacritty/alacritty.toml
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

#normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
#bold = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
#italic = { family = "MesloLGS Nerd Font Mono", style = "Italic" }
#bold_italic = { family = "MesloLGS Nerd Font Mono", style = "Bold Italic" }


#normal = { family = "MesloLGS NF", style = "Regular" }
#bold = { family = "MesloLGS NF", style = "Bold" }
#italic = { family = "MesloLGS NF", style = "Italic" }
#bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }
size = 14

[window]
opacity = 0.95
padding = { x = 8, y = 8 }

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"
